version: '3.9'

services:
    jenkins:
        image: jenkins/jenkins
        ports:
          - 8580:80
          - 50000:50000
        networks:
          - jenkins-network
    ubuntu:
        image: ubuntu:18.04
        build: ./panda_ubuntu
        networks:
          - jenkins-network

networks:
    jenkins-network: 
